version: 0.1
targets:
  default: csharp
documents:
  template: markdown.question-tree
docs-standard:
  source: https://github.com/vslices/docs-standard
  ref: main
template-standard:
  source: https://github.com/vslices/template-standard
  ref: main
lineage:
  bootstrap:
    convention: existing-materialization
updates:
  source: https://github.com/vslices/tooling
  channel: build
  pull-request: 10
...
